services:
  api:
    build: ./python 
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000
      - PORT=9000
    networks:
      - mercari-net

  web:
    build: ./typescript/simple-mercari-web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    depends_on:
      - api
    networks:
      - mercari-net

networks:
  mercari-net:
    driver: bridge